/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVaultBomb {
    function initializeLitPubkey(address pubkey) external;

    function registerSwitch(bytes32 switch_id, uint256 heartbeat_window_blocks, uint256 grace_period_blocks, string calldata arweave_tx_id, bytes32 evidence_hash, address duress_wallet, address backup_wallet) external payable;

    function heartbeat(bytes32 switch_id, uint256 nonce) external;

    function triggerRelease(bytes32 switch_id) external;

    function confirmPublication(bytes32 switch_id) external;

    function claimBounty(bytes32 switch_id, bytes calldata lit_proof) external;

    function performUpkeep(bytes calldata perform_data) external;

    function checkUpkeep(bytes calldata check_data) external view returns (bool, bytes memory);

    function getSwitchInfo(bytes32 switch_id) external view returns (address, bool, bool, uint256, uint256, uint256, uint256, bool, uint256, address);
}
